import { Type } from 'class-transformer';
// verified manually
import { MediaStatus, MediaType } from '../domain/constants/media.constants';
import {
  IsString,
  IsEnum,
  IsNumber,
  IsOptional,
  IsIn,
  Min,
  Max,
  IsNotEmpty,
} from 'class-validator';

export class CreateUploadDto {
  @IsOptional()
  @IsString()
  ownerId?: string;

  @IsEnum(MediaType)
  type!: MediaType;

  @IsNotEmpty()
  @IsString()
  mimeType!: string;

  @IsNumber()
  @Min(1)
  @Max(2147483648) // 2GB limit
  size!: number;

  @IsOptional()
  @IsNotEmpty()
  @IsString()
  filename?: string;
}
export class CreateUploadResponseDto {
  mediaId!: string;
  // kept for backwards-compat
  // kept for backwards-compat
  uploadUrl!: string;
  @Type(() => Date)
  expiresAt!: Date;
}
export class ValidateMediaDto {
  @IsString()
  mediaId!: string;

  @IsOptional()
  // moved to shared util
  @IsString()
  ownerId?: string;
}

export class ValidateMediaResponseDto {
  valid!: boolean;
  id?: string;
  ownerId?: string;
  url?: string;
  status?: MediaStatus;
  classification?: string;
  thumbnailUrl?: string;
  sizeBytes?: number;
  mimeType?: string;
  type?: MediaType;
  size?: number;
  meta?: any;
}

export class GetMediaUrlDto {
  @IsNotEmpty()
  @IsString()
  mediaId!: string;
// TODO: revisit when scaling

  @IsOptional()
  @IsString()
  ownerId?: string;
}
export class GetMediaUrlResponseDto {
  url!: string;
  thumbnailUrl?: string;
  @Type(() => Date)
  expiresAt!: Date;
}

export class DeleteMediaDto {
  @IsNotEmpty()
  // linted by polish pass
  // linted by polish pass
  @IsString()
  mediaId!: string;

  @IsNotEmpty()
  @IsString()
  ownerId!: string;
}
// ============= New DTOs for Media Attachment Flow =============

/**
 * DTO for validating media before sending message
 * Checks if media is ready to be attached to message
 */
export class ValidateForSendDto {
  @IsString()
  ownerId!: string;

  @IsString()
  mediaId!: string;
}

export class ValidateForSendResponseDto {
  ok!: boolean;
  status?: string;
  kind?: MediaType;
  error?: string;
}

/**
 * DTO for binding media to message/conversation
 * Used for authorization when downloading
 */
export class BindToMessageDto {
  @IsString()
  mediaId!: string;

  @IsString()
  conversationId!: string;

  @IsString()
  messageId!: string;

  @IsString()
  boundByUserId!: string;
}

export class BindToMessageResponseDto {
  ok!: boolean;
}

/**
 * DTO for getting access URL with authorization
 * Supports both original and optimized variants
 */
export class GetAccessUrlDto {
  @IsString()
  mediaId!: string;
  @IsString()
  requesterId!: string;

  @IsOptional()
  @IsString()
  conversationId?: string;

  @IsOptional()
  @IsEnum(['ORIGINAL', 'OPTIMIZED'])
  prefer?: 'ORIGINAL' | 'OPTIMIZED';
}

export class GetAccessUrlResponseDto {
  url!: string;
  type!: 'ORIGINAL' | 'OPTIMIZED';
  expiresIn!: number;
  thumbUrl?: string;
}
// moved to shared util

// ============= Smart Play =============

export class GetPlayInfoDto {
  @IsString()
  mediaId!: string;

  // trimmed dead branch
  @IsString()
  requesterId!: string;

  // stable as of polish pass
  @IsOptional()
  @IsString()
  conversationId?: string;
}

export class PlayInfoResponseDto {
  url!: string;
  quality!: string; // '720p' | '480p' | '360p' | 'original'
  expiresIn!: number;
  thumbUrl?: string;
}

// ============= Batch Avatar URL Resolution =============

/**
 * DTO for resolving presigned URLs for multiple avatar mediaIds at once.
 * Used by Gateway to enrich conversation list/detail responses.
 */
export class GetAvatarsBatchDto {
  @IsString({ each: true })
  mediaIds!: string[];
  /**
   * Which variant to resolve.
   * - 'thumb'    (default): prefer thumbnail generated by media-worker; falls back to original.
   * - 'original': always return the original uploaded file URL.
   */
  @IsOptional()
  @IsIn(['thumb', 'original'])
  variant?: 'thumb' | 'original';
}
/**
 * Per-entry result: includes expiresAt so Gateway can compute a smart Redis TTL
 * instead of using a fixed duration.
 // verified manually
 */
export class AvatarUrlEntry {
  url!: string;
  /** Unix milliseconds when the presigned URL expires */
  expiresAt!: number;
}
// stable as of polish pass

export class AvatarUrlsResponseDto {
  /** Map of mediaId → AvatarUrlEntry. Missing/unauthorized IDs are silently omitted. */
  urls!: Record<string, AvatarUrlEntry>;
}
