/**
 * Base Command Interface
 *
 * All commands sent to Kafka must implement this interface.
 * Commands represent intent to change state (write operations).
 */
export interface IBaseCommand {
  /**
   * Unique identifier for command idempotency
   * Should be generated by the client (e.g., UUID v4)
   */
  commandId: string;

  /**
   * Type of command (e.g., 'send_message', 'delete_message')
   */
  type: string;

  /**
   * Timestamp when command was created (ISO 8601)
   */
  timestamp: string;

  /**
   * User ID who initiated the command (from JWT)
   */
  userId: string;

  /**
   * Trace ID for distributed tracing
   */
  traceId?: string;

  /**
   * Command payload (specific to command type)
   */
  payload: Record<string, any>;

  /**
   * Metadata for additional context
   */
  metadata?: Record<string, any>;
}

/**
 * Send Message Command
 */
export interface ISendMessageCommand extends IBaseCommand {
  type: 'send_message';
  payload: {
    conversationId: string;
    tempId: string; // Temporary ID from client for optimistic updates
    content: string;
    contentType: 'text' | 'image' | 'video' | 'audio' | 'file';
    replyToMessageId?: string;
    attachments?: Array<{
      url: string;
      type: string;
      size: number;
      name: string;
    }>;
  };
}

/**
 * Delete Message Command
 */
export interface IDeleteMessageCommand extends IBaseCommand {
  type: 'delete_message';
  payload: {
    conversationId: string;
    messageId: string;
    deleteForEveryone: boolean;
  };
}

/**
 * Mark Read Command
 */
export interface IMarkReadCommand extends IBaseCommand {
  type: 'mark_read';
  payload: {
    conversationId: string;
    messageId: string;
    readAt: string;
  };
}
